### ISSUE TITLE
Access violation reading

### ISSUE THREAD

**Issue by TokyoSU** [BadDogSkyrim/PyNifly#174] opened 2023-09-09 14:30 UTC
[SkyrimLE,Blender3.6]
Getting this error trying to open a .nif:
![error_lumber](https://github.com/BadDogSkyrim/PyNifly/assets/77746747/a6dfc7dd-e8eb-4f96-a3da-b2d21696ed45)

**Comment by BadDogSkyrim** [comment] 2023-09-10 00:07
Duplicate of your other bug report.

**Closed by BadDogSkyrim** 2023-09-10 00:07 UTC
Labels: duplicate
