### ISSUE TITLE
Importing SkyrimSE nif fails

### ISSUE THREAD

**Issue by Jerickman** [BadDogSkyrim/PyNifly#119] opened 2022-08-10 17:44 UTC
Plugin v5.8.2
Blender 3.2

Importing Skyrim SE nif file fails. Error message reads "Import of nif failed, see console window for details"

No details are visible in Blender's console window

**Comment by Jerickman** [comment] 2022-08-10 17:51
Tested on Blender 2.93 with same result

**Comment by BadDogSkyrim** [comment] 2022-08-11 07:38
Which nif fails? Do any nifs work?

**Comment by Jerickman** [comment] 2022-08-21 22:05
Every nif I threw at it failed, either extracted from the game or from mod files.

**Comment by BadDogSkyrim** [comment] 2022-08-22 00:40
Sounds like an installation problem.

Load up a new Blender instance Open the console window. Do you see a line "INFO:pynifly:Loading pynifly version 5.9.0"? If not, figure out how the install got borked.

If it's there, there's probably something else in your setup that's wrong but I'm not sure what that would be. Exp/Imp of OBJ files works?

**Comment by LittleMissF** [comment] 2022-09-11 16:17
Hi there!

I might have a similar issue and panic a bit atm, because I am mainly modding headparts. Exporting headparts for Skyrim SE suddenly crashes game. I tried now several headparts, reinstalled blender, tried different versions(2.93.1, 3.0, 3.3) different plug-in versions, reinstalled plug-ins. The only thing I didn’t do is reinstalling my pythons. I asked now if someone in the modding community I am in could export a headpart for me and I see if it’s crashing, too. See if the error is reproduced. I know I post this probably wrong, but my brain isn’t working so well in my panic. 

Greets Frannie

**Comment by BadDogSkyrim** [comment] 2022-09-24 12:21
Closing for lack of info.

**Closed by BadDogSkyrim** 2022-09-24 12:21 UTC
