### ISSUE TITLE
Skinned Meshes don't export properly(messed up in-game)

### ISSUE THREAD

**Issue by Sammy-0** [BadDogSkyrim/PyNifly#103] opened 2022-05-02 00:23 UTC

**Comment by BadDogSkyrim** [comment] 2022-05-04 23:17
Okay, this is a totally useless bug report and I'm closing it if you don't give me more info w/in a few days.

I assume you have some skinned mesh which isn't exporting properly. Many (many many) others export just fine, so there's something special about yours. You need to send me the .blend file so I can check it out or provide lots more detail about what the problem is.

**Comment by Sammy-0** [comment] 2022-05-04 23:27
no idea but im not home rn. ill try another model later but

1: Imported model(seam between hand and body)
2: Fix seam by merging vertices between forearm and hand
3: Try to export, model gets screwed up in-game. all distorted i mean

what i noticed was that vertex groups weren't in the same order and in nifskope nodes were missing.

**Comment by BadDogSkyrim** [comment] 2022-05-05 11:56
If you really mean merging vertices, you have to have joined the meshes and you'll have to split them again before exporting. AND you'll have to export both body and hands, and you probably don't really want to replace the body.

If you mean that you snapped each hand vertex to the wrist position, and copied weights from wrist vert to hand vert (you can hope they're the same but you should check), and then exported, then you have to say more about what's missing and how the mesh is distorted. 

Vertex group order doesn't matter.

**Closed** 2022-05-10 23:34 UTC
